
title: Tom Ray
email: tmray1@gmail.com
description: My old blog. Currently I'm running an art podcast, drawing a daily webcomic and vlogging at this website tomrayswebsite.com. # the description on homepage is in the index.html yaml I should change that.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tmray.github.io" # the base hostname & protocol for your site, e.g. https://example.com


# Build settings
markdown: kramdown
#theme: beautiful-jekyll-theme
paginate: 5

plugins:
  - jekyll-paginate
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

# navigation
navbar-links:
  Home: ""
  About Me: "about"
  # Resources:
  #   - Beautiful Jekyll: "https://deanattali.com/beautiful-jekyll/"
  #   - Learn markdown: "https://www.markdowntutorial.com/"
  #   - GitHub Pages: "https://pages.github.com/"
  # Author's home: "https://deanattali.com"

# image icon
avatar: "/public/images/profile_400x400.jpg"

permalink: pretty

# social in footer
author:
  name: Tom Ray
  email: "tmray1@gmail.com"
  facebook: tmray1  # eg. daattali
  github: tmray    # eg. daattali
  twitter: tmray   # eg. daattali
  # telephone: yourphone     # eg. +14159998888
  # reddit: yourname    # eg. daattali
  # google-plus: +yourname   # eg. +DeanAttali or 109424658772469020925
  # linkedin: yourname  # eg. daattali
  # xing: yourname      # eg. daattali
  # stackoverflow: yourlink  # eg. "3943160/daattali"
  # snapchat: yourname  # eg. daattali
  instagram: tmray # eg. daattali
  youtube: tmray   # eg. user/daattali or channel/daattali
  # spotify: yourname   # eg. daattali

# feed
rss-footer: true

url-pretty: "tmray.github.io"

# post buttons
share-links-active:
  twitter: true
  facebook: true
  google: false
  linkedin: false

# if wanting comments
# disqus: yourshortname

# Google Analytics (this is my old blog one, may need to update)
# google_analytics: UA-327863-4

# Collection folders
collections:
  collection:
    output: true
