# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               Tom Ray
tagline:             'Just a blog.'
description:         'The thoughts of a man who has nothing relevant on his mind. Made by <a href="https://twitter.com/tmray" target="_blank">@tmray</a>.'
url:                 http://tmray.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Tom Ray
  url:               https://twitter.com/tmray
  email:             tmray1@gmail.com
  twitter_username:  tmray

# Custom vars
version:             0.4

github:
  repo:              https://github.com/tmray/tmray.github.com

gems: [jekyll-paginate, jekyll-gist]
