
title: Tom Ray
description: My blog. Currently I'm obsessed with mini-comics and mix tapes. My interests can change at any moment.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tmray.github.io" # the base hostname & protocol for your site, e.g. http://example.com

############################################################
# Site configuration for the Jekyll 3 Pagination Gem
# The values here represent the defaults if nothing is set
pagination:

  # Site-wide kill switch, disabled here it doesn't run at all
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false

  # The default document collection to paginate if nothing is specified ('posts' is default)
  collection: 'posts'

  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 5

  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: '/page:num/' # Pages are index.html inside this folder (default)
  #permalink: '/page/:num.html' # Pages are simple html files
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.

  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  title: ':title'

  # Limit how many pagenated pages to create (default: 0, means all)
  limit: 0

  # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
  sort_field: 'date'

  # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
  sort_reverse: true

  # Optional, the default category to use, omit or just leave this as 'posts' to get a backwards-compatible behavior (all posts)
  category: 'posts'

  # Optional, the default tag to use, omit to disable
  tag: ''

  # Optional, the default locale to use, omit to disable (depends on a field 'locale' to be specified in the posts,
  # in reality this can be any value, suggested are the Microsoft locale-codes (e.g. en_US, en_GB) or simply the ISO-639 language code )
  locale: ''

 # Optional,omit or set both before and after to zero to disable.
 # Controls how the pagination trail for the paginated pages look like.
  trail:
    before: 2
    after: 2

############################################################

# Build settings
markdown: kramdown
#theme: beautiful-jekyll-theme
#paginate: 5

gems:
  - jekyll-paginate-v2
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

# navigation
navbar-links:
  Home: ""
  Comics:
    - Then this happened: "comics/then-this-happened/"
  About Me: "about"
  # Resources:
  #   - Beautiful Jekyll: "http://deanattali.com/beautiful-jekyll/"
  #   - Learn markdown: "http://www.markdowntutorial.com/"
  #   - GitHub Pages: "https://pages.github.com/"
  # Author's home: "http://deanattali.com"

# image icon
avatar: "/public/images/profile_400x400.jpg"

permalink: pretty

# social in footer
author:
  name: Tom Ray
  email: "tmray1@gmail.com"
  facebook: tmray1  # eg. daattali
  github: tmray    # eg. daattali
  twitter: tmray   # eg. daattali
  youtube: tmray   # eg. user/daattali or channel/daattali
  # telephone: yourphone     # eg. +14159998888
  # reddit: yourname    # eg. daattali
  # google-plus: +yourname   # eg. +DeanAttali or 109424658772469020925
  # linkedin: yourname  # eg. daattali
  # xing: yourname      # eg. daattali
  # stackoverflow: yourlink  # eg. "3943160/daattali"
  # snapchat: yourname  # eg. daattali
  # instagram: yourname # eg. daattali
  # spotify: yourname   # eg. daattali

# Select which links to show in the footer
footer-links-active:
  rss: true
  facebook: true
  email: true
  twitter: true
  google-plus: false
  github: false
  reddit: false
  linkedin: false
  xing: false
  stackoverflow: false
  snapchat: false
  instagram: false
  youtube: true
  spotify: false
  telephone: false

url-pretty: "tmray.github.io"

# post buttons
share-links-active:
  twitter: true
  facebook: true
  google: false
  linkedin: false

# if wanting comments
# disqus: yourshortname

# Google Analytics (this is my old blog one, may need to update)
google_analytics: UA-327863-4

# Collection folders
collections:
  collection:
    output: true
  category:
    output: true
