# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Tom Ray
email: tmray1@gmail.com
description: My blog. Currently I'm obsessed with mini-comics and mix tapes. My interests can change at any moment.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tmray.github.io" # the base hostname & protocol for your site, e.g. http://example.com


# Build settings
markdown: kramdown
theme: beautiful-jekyll-theme
paginate: 5
gems:
  - jekyll-paginate
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

# navigation
navbar-links:
  Home: ""
  About Me: "about"
  # Resources:
  #   - Beautiful Jekyll: "http://deanattali.com/beautiful-jekyll/"
  #   - Learn markdown: "http://www.markdowntutorial.com/"
  #   - GitHub Pages: "https://pages.github.com/"
  # Author's home: "http://deanattali.com"

# image icon
avatar: "https://pbs.twimg.com/profile_images/827176612768649216/n1qbvhIl_400x400.jpg"

# social in footer
author:
  name: Tom Ray
  email: "tmray1@gmail.com"
  facebook: tmray1  # eg. daattali
  github: tmray    # eg. daattali
  twitter: tmray   # eg. daattali
  # telephone: yourphone     # eg. +14159998888
  # reddit: yourname    # eg. daattali
  # google-plus: +yourname   # eg. +DeanAttali or 109424658772469020925
  # linkedin: yourname  # eg. daattali
  # xing: yourname      # eg. daattali
  # stackoverflow: yourlink  # eg. "3943160/daattali"
  # snapchat: yourname  # eg. daattali
  # instagram: yourname # eg. daattali
  youtube: tmray   # eg. user/daattali or channel/daattali
  # spotify: yourname   # eg. daattali

# feed
rss-footer: true

url-pretty: "tmray.github.io"

# post buttons
share-links-active:
  twitter: true
  facebook: true
  google: false
  linkedin: false

# if wanting comments
# disqus: yourshortname

# Google Analytics (this is my old blog one, may need to update)
google_analytics: UA-327863-4

# Collection folders
collections:
  collection:
    output: true
